# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ggjiji/Project/Accelator/Accelator.srcs/sources_1/ip/parameter_sram/parameter_sram.xci
# IP: The module: 'parameter_sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ggjiji/Project/Accelator/Accelator.srcs/sources_1/ip/parameter_sram/parameter_sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'parameter_sram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ggjiji/Project/Accelator/Accelator.srcs/sources_1/ip/parameter_sram/parameter_sram.xci
# IP: The module: 'parameter_sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ggjiji/Project/Accelator/Accelator.srcs/sources_1/ip/parameter_sram/parameter_sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'parameter_sram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
